name: rag-qa-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - langchain
    - langchain-chroma
    - langchain-community
    - langchain-core
    - langchain-groq
    - langchain-huggingface
    - langchain-text-splitters
    - python-dotenv
    - pypdf
    - chromadb
    - sentence-transformers
    - huggingface-hub
